name: paulpaino
favicon: null
layout_spectrum: 0.9113749228417873
typography_spectrum: 0.31836298014968634
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.6349647077731788
  lightness: 0.7857506193686277
  saturation: 0.9325006271246821
  rhythmicContrast: 0.7023470348212868
purpose: []
